import "@/styles/globals.css";

// import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

// Font
import { montserrat } from "@/fonts";

// Components
// import { Toaster } from "@/components/ui";
import { Navbar } from "@/components/admin/Layout";
import { Providers } from "@/utils/Providers";
import { auth } from "@/server/auth";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function SuperAdminLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  return (
    <html lang="en" className={`${montserrat.className}`}>
      <body>
        <Providers session={session}>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
